import './globals.css'
import { Inter } from 'next/font/google'
import  Navbar from '../components/Navbar/index'
import pfcLogo from '../assets/pfcLogo.png'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href={pfcLogo.src} />
        <title>UNSW pfc</title>
      </head>
      <body className='global-body'>
        <Navbar />
        {children}
      </body>
      <head>
        <link rel="icon" href={pfcLogo.src} />
        <title>UNSW pfc</title>
      </head>
    </html>
  )
}
